import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header";
import ReduxProvider from "./ReduxProvider";
import UserLoader from "./UserLoader";
import { Toaster } from "@/components/ui/sonner";
import NotificationProvider from "@/components/NotificationProvider";
import LoginModal from "@/components/LoginModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <UserLoader />
          <NotificationProvider>
            <Header />
            {children}
            <LoginModal />
            <Toaster />
          </NotificationProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
